groups:
- name: invalid-jwt
  rules:
    - alert: HighExpiredJwtCount
      expr: increase(adm_backend_expired_jwt_sum_total[20s]) > 5
      labels:
        severity: critical
      annotations:
        summary: "High number of expired JWTs detected"
        description: "The number of expired JWT has exceeded 5 in the last 20s"