global:
  scrape_interval: 10s
alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alert-manager:9093']
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'adm-backend'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['adm-backend:5000']

rule_files:
  - "alert_rules.yml"